"""Read-only Kibana log-query MCP server for production log investigation.

The server never connects to Elasticsearch directly. It sends read-only search
requests to Kibana's internal msearch endpoint using a configured ``sid`` cookie.
"""

from __future__ import annotations

import json
import os
import re
import sys
import uuid
from datetime import datetime, timedelta, timezone
from functools import lru_cache
from typing import Any, Dict, Iterable, List, Optional
from urllib.error import HTTPError, URLError
from urllib.parse import urlparse
from urllib.request import Request, urlopen

from mcp.server import MCPServer


MAX_RESULTS = 200
MAX_PAGINATED_RESULTS = 1000
DEFAULT_SOURCE_FIELDS = ["@timestamp", "level", "appname", "traceId", "message", "host.name"]
SAFE_NAME = re.compile(r"^[A-Za-z0-9_@.*?,:+-]+$")
DATE_MATH = re.compile(r"now(?:[+-]\d+[smhdwMy])?(?:/[smhdwMy])?")
SENSITIVE_FIELD = re.compile(r"(?:authorization|cookie|password|secret|token|sid)", re.IGNORECASE)
SENSITIVE_VALUE = re.compile(
    r"(?i)(\b(?:authorization|cookie|password|secret|token|sid)\b\s*[:=]\s*[\"']?)([^\s,;\"'\]\}]+)"
)
SENSITIVE_BRACKET_VALUE = re.compile(
    r"(?i)(\b(?:authorization|cookie|password|secret|token|sid)\b\s*[【\[])(.*?)([】\]])"
)


server = MCPServer(
    name="kibana-logs",
    title="Kibana Production Log Query",
    description="Read-only production log investigation through Kibana.",
    instructions=(
        "Use a short time range first. Search results are read-only and sensitive "
        "credential-like values are automatically redacted."
    ),
)


class KibanaRequestError(RuntimeError):
    """A safe, user-visible failure from the Kibana proxy."""


def _clean_sid(raw_sid: str) -> str:
    sid = raw_sid.strip()
    if sid.lower().startswith("sid="):
        sid = sid[4:].split(";", 1)[0].strip()
    if not sid:
        raise KibanaRequestError("未配置 KIBANA_SID")
    return sid


class KibanaClient:
    """Small, stdlib-only client for Kibana's internal msearch endpoint."""

    def __init__(self) -> None:
        base_url = os.getenv("KIBANA_BASE_URL", "").strip().rstrip("/")
        parsed = urlparse(base_url)
        if parsed.scheme != "https" or not parsed.netloc:
            raise KibanaRequestError("KIBANA_BASE_URL 必须是有效的 https 地址")

        self.base_url = base_url
        self.sid = _clean_sid(os.getenv("KIBANA_SID", ""))
        self.version = os.getenv("KIBANA_VERSION", "7.13.0").strip() or "7.13.0"
        try:
            self.timeout_seconds = max(1, min(int(os.getenv("KIBANA_TIMEOUT_SECONDS", "15")), 60))
        except ValueError as exc:
            raise KibanaRequestError("KIBANA_TIMEOUT_SECONDS 必须是整数") from exc

    def msearch(self, params: Dict[str, Any]) -> Dict[str, Any]:
        """Run one Kibana msearch request without exposing the session cookie.

        ``/internal/bsearch`` validates an opaque identifier generated by the
        Kibana browser application.  ``/internal/_msearch`` accepts the same
        read-only Elasticsearch request as a JSON ``searches`` array and has
        no browser-only id.
        """
        encoded = _build_msearch_payload(params)
        request = Request(
            f"{self.base_url}/internal/_msearch",
            data=encoded,
            method="POST",
            headers={
                "Content-Type": "application/json",
                "Cookie": f"sid={self.sid}",
                "kbn-version": self.version,
                "kbn-xsrf": "kibana-mcp",
                "Origin": self.base_url,
                "Referer": f"{self.base_url}/app/discover",
                "User-Agent": "kibana-mcp-readonly/1.0",
            },
        )
        try:
            with urlopen(request, timeout=self.timeout_seconds) as response:
                payload = json.loads(response.read().decode("utf-8"))
                if isinstance(payload, dict):
                    payload = dict(payload)
                    payload["_mcp_http_status"] = response.status
                if os.getenv("KIBANA_DEBUG_RESPONSE", "").strip().lower() in {"1", "true", "yes", "on"}:
                    print(
                        json.dumps(
                            {
                                "http_status": response.status,
                                "content_type": response.headers.get("Content-Type"),
                                "response": _redact(payload),
                            },
                            ensure_ascii=False,
                        ),
                        file=sys.stderr,
                        flush=True,
                    )
                return payload
        except HTTPError as exc:
            if exc.code in (401, 403):
                raise KibanaRequestError(
                    f"Kibana 权限验证失败（HTTP {exc.code}），登录态无效或已过期，请更新 KIBANA_SID"
                ) from exc
            raise KibanaRequestError(f"Kibana 查询失败（HTTP {exc.code}）") from exc
        except URLError as exc:
            raise KibanaRequestError(f"无法连接 Kibana：{exc.reason}") from exc
        except TimeoutError as exc:
            raise KibanaRequestError("Kibana 查询超时") from exc
        except (UnicodeDecodeError, json.JSONDecodeError) as exc:
            raise KibanaRequestError("Kibana 返回了无法解析的响应") from exc


@lru_cache(maxsize=1)
def get_client() -> KibanaClient:
    return KibanaClient()


def _validate_name(value: str, label: str, allow_comma: bool = True) -> str:
    if not value or not SAFE_NAME.fullmatch(value):
        raise ValueError(f"{label} 包含不允许的字符")
    if not allow_comma and "," in value:
        raise ValueError(f"{label} 不允许包含逗号")
    return value


def _clean_size(size: int) -> int:
    if size < 1:
        raise ValueError("size 必须大于 0")
    return min(size, MAX_RESULTS)


def _clean_max_results(max_results: int) -> int:
    if max_results < 1:
        raise ValueError("max_results 必须大于 0")
    return min(max_results, MAX_PAGINATED_RESULTS)


def _parse_time(value: str, field_name: str) -> str:
    value = value.strip()
    if value.startswith("now"):
        if not DATE_MATH.fullmatch(value):
            raise ValueError(f"{field_name} 不是有效的 Elasticsearch date math")
        return value
    try:
        datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as exc:
        raise ValueError(f"{field_name} 必须是 ISO-8601 时间或 now-1h 形式") from exc
    return value


def _default_index() -> str:
    return os.getenv("KIBANA_DEFAULT_INDEX", "logstash-filebeat-*").strip() or "logstash-filebeat-*"


def _redact(value: Any, field_name: str = "") -> Any:
    """Avoid returning credentials that may occur in production log payloads."""
    if SENSITIVE_FIELD.search(field_name):
        return "[REDACTED]"
    if isinstance(value, dict):
        return {key: _redact(item, key) for key, item in value.items()}
    if isinstance(value, list):
        return [_redact(item, field_name) for item in value]
    if isinstance(value, str):
        value = SENSITIVE_VALUE.sub(r"\1[REDACTED]", value)
        return SENSITIVE_BRACKET_VALUE.sub(r"\1[REDACTED]\3", value)
    return value


def _field_value(value: Any) -> Any:
    if isinstance(value, list) and len(value) == 1:
        return value[0]
    return value


def _extract_raw_response(payload: Any, http_status: Optional[int] = None) -> Dict[str, Any]:
    """Handle response shapes used by Kibana 7.x internal search APIs."""
    if isinstance(payload, dict):
        http_status = payload.get("_mcp_http_status", http_status)
        if isinstance(payload.get("body"), dict):
            return _extract_raw_response(payload["body"], http_status)
        if isinstance(payload.get("rawResponse"), dict):
            return payload["rawResponse"]
        if isinstance(payload.get("hits"), dict):
            return payload
        for key in ("responses", "batch"):
            entries = payload.get(key)
            if isinstance(entries, list) and entries:
                return _extract_raw_response(entries[0], http_status)
        if isinstance(payload.get("response"), dict):
            return _extract_raw_response(payload["response"], http_status)
    if isinstance(payload, list) and payload:
        return _extract_raw_response(payload[0], http_status)
    if isinstance(payload, dict):
        visible = {key: value for key, value in payload.items() if not key.startswith("_mcp_")}
        details = json.dumps(_redact(visible), ensure_ascii=False)[:2000]
        raise KibanaRequestError(
            f"Kibana 查询响应无法解析（HTTP {http_status or 'unknown'}，已脱敏原始返回：{details}）"
        )
    raise KibanaRequestError(f"Kibana 查询响应无法解析（HTTP {http_status or 'unknown'}）")


def _total_value(total: Any) -> int:
    if isinstance(total, dict):
        return int(total.get("value", 0))
    return int(total or 0)


def _search_response(raw_response: Dict[str, Any]) -> Dict[str, Any]:
    hits = raw_response.get("hits", {})
    logs = []
    for hit in hits.get("hits", []):
        item: Dict[str, Any] = {
            "_index": hit.get("_index"),
            "_id": hit.get("_id"),
            "_score": hit.get("_score"),
        }
        if isinstance(hit.get("_source"), dict):
            item.update(hit["_source"])
        if isinstance(hit.get("fields"), dict):
            item.update({key: _field_value(value) for key, value in hit["fields"].items()})
        if "sort" in hit:
            item["_sort"] = hit["sort"]
        logs.append(_redact(item))
    return {
        "ok": True,
        "total": _total_value(hits.get("total")),
        "returned": len(logs),
        "timed_out": bool(raw_response.get("timed_out", False)),
        "logs": logs,
    }


def _build_query(
    query: str,
    start_time: Optional[str],
    end_time: Optional[str],
    time_field: str,
    filters: Optional[Dict[str, Any]],
) -> Dict[str, Any]:
    must: List[Dict[str, Any]] = []
    filter_clauses: List[Dict[str, Any]] = []
    if query.strip():
        must.append({"multi_match": {"type": "phrase", "query": query.strip(), "lenient": True}})
    else:
        must.append({"match_all": {}})
    if start_time or end_time:
        _validate_name(time_field, "time_field", allow_comma=False)
        time_range: Dict[str, str] = {}
        if start_time:
            time_range["gte"] = _parse_time(start_time, "start_time")
        if end_time:
            time_range["lte"] = _parse_time(end_time, "end_time")
        filter_clauses.append({"range": {time_field: time_range}})
    for field, value in (filters or {}).items():
        _validate_name(field, "过滤字段", allow_comma=False)
        if isinstance(value, list):
            filter_clauses.append({"terms": {field: value}})
        else:
            filter_clauses.append({"term": {field: value}})
    return {"bool": {"must": must, "filter": filter_clauses}}


def _build_params(
    index: str,
    query: str,
    start_time: Optional[str],
    end_time: Optional[str],
    time_field: str,
    filters: Optional[Dict[str, Any]],
    size: int,
    source_fields: Iterable[str],
    sort_order: str,
    aggs: Optional[Dict[str, Any]] = None,
    search_after: Optional[List[Any]] = None,
) -> Dict[str, Any]:
    _validate_name(index, "index")
    _validate_name(time_field, "time_field", allow_comma=False)
    if sort_order not in ("asc", "desc"):
        raise ValueError("sort_order 只能是 asc 或 desc")
    fields = []
    for field in dict.fromkeys(source_fields):
        _validate_name(field, "source_fields 字段", allow_comma=False)
        spec: Dict[str, Any] = {"field": field, "include_unmapped": True}
        if field == time_field:
            spec["format"] = "strict_date_optional_time"
        fields.append(spec)
    body: Dict[str, Any] = {
        "size": size,
        "sort": [
            {time_field: {"order": sort_order, "unmapped_type": "boolean"}},
            {"_shard_doc": {"order": "asc"}},
        ],
        "track_total_hits": True,
        "fields": fields,
        "stored_fields": ["*"],
        "runtime_mappings": {},
        "_source": False,
        "query": _build_query(query, start_time, end_time, time_field, filters),
    }
    if aggs:
        body["aggs"] = aggs
    if search_after is not None:
        body["search_after"] = search_after
    return {
        "index": index,
        "body": body,
        "preference": str(uuid.uuid4().int),
    }


def _build_msearch_payload(params: Dict[str, Any]) -> bytes:
    """Build the JSON wrapper expected by Kibana 7.13's internal msearch route.

    This is intentionally not Elasticsearch's native NDJSON ``_msearch``
    format.  Kibana's ``/internal/_msearch`` validates a JSON object with a
    ``searches`` array, then converts it to the Elasticsearch request itself.
    """
    header = {
        "index": params["index"],
        "preference": params["preference"],
    }
    payload = {"searches": [{"header": header, "body": params["body"]}]}
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")


def _run_search(**kwargs: Any) -> Dict[str, Any]:
    return _extract_raw_response(get_client().msearch(_build_params(**kwargs)))


def _run_paginated_search(
    *,
    page_size: int,
    max_results: int,
    **kwargs: Any,
) -> Dict[str, Any]:
    """Fetch all pages using search_after and merge results without duplicates."""
    page_size = _clean_size(page_size)
    max_results = _clean_max_results(max_results)
    search_after: Optional[List[Any]] = None
    logs: List[Dict[str, Any]] = []
    seen = set()
    total = 0
    pages = 0
    timed_out = False

    while len(logs) < max_results:
        raw = _run_search(
            **kwargs,
            size=min(page_size, max_results - len(logs)),
            search_after=search_after,
        )
        page = _search_response(raw)
        pages += 1
        total = max(total, page["total"])
        timed_out = timed_out or page["timed_out"]
        page_logs = page["logs"]

        for item in page_logs:
            key = (item.get("_index"), item.get("_id"))
            if key in seen:
                continue
            seen.add(key)
            logs.append(item)
            if len(logs) >= max_results:
                break

        if not page_logs or len(logs) >= total or len(logs) >= max_results:
            break
        next_search_after = page_logs[-1].get("_sort")
        if not isinstance(next_search_after, list) or next_search_after == search_after:
            raise KibanaRequestError("分页响应缺少有效的 search_after 排序值")
        search_after = next_search_after

    return {
        "ok": True,
        "total": total,
        "returned": len(logs),
        "pages": pages,
        "truncated": total > len(logs),
        "timed_out": timed_out,
        "logs": logs,
    }


def _error(exc: Exception) -> Dict[str, Any]:
    return {"ok": False, "error": _redact(str(exc))}


@server.tool()
def check_connection() -> Dict[str, Any]:
    """检查 Kibana 是否可访问，以及 KIBANA_SID 是否仍然有效。"""
    try:
        raw = _run_search(
            index=_default_index(),
            query="",
            start_time="now-1m",
            end_time="now",
            time_field="@timestamp",
            filters=None,
            size=0,
            source_fields=[],
            sort_order="desc",
        )
        return {"ok": True, "total_in_last_minute": _total_value(raw.get("hits", {}).get("total"))}
    except Exception as exc:
        return _error(exc)


@server.tool()
def search_logs(
    query: str = "",
    index: Optional[str] = None,
    start_time: Optional[str] = "now-1h",
    end_time: Optional[str] = "now",
    time_field: str = "@timestamp",
    filters: Optional[Dict[str, Any]] = None,
    size: int = 50,
    source_fields: Optional[List[str]] = None,
    sort_order: str = "desc",
    max_results: int = 1000,
) -> Dict[str, Any]:
    """通过 Kibana 查询日志。query 是短语匹配；filters 用于精确字段过滤。"""
    try:
        return _run_paginated_search(
            index=index or _default_index(),
            query=query,
            start_time=start_time,
            end_time=end_time,
            time_field=time_field,
            filters=filters,
            source_fields=source_fields or DEFAULT_SOURCE_FIELDS,
            sort_order=sort_order,
            page_size=size,
            max_results=max_results,
        )
    except Exception as exc:
        return _error(exc)


@server.tool()
def get_trace_logs(
    trace_id: str,
    index: Optional[str] = None,
    start_time: Optional[str] = "now-1d",
    end_time: Optional[str] = "now",
    size: int = 100,
) -> Dict[str, Any]:
    """按 traceId 查询日志链路。"""
    return search_logs(
        query=trace_id,
        index=index,
        start_time=start_time,
        end_time=end_time,
        size=size,
        sort_order="asc",
    )


@server.tool()
def get_log_context(
    timestamp: str,
    query: str = "",
    index: Optional[str] = None,
    minutes_before: int = 2,
    minutes_after: int = 2,
    size: int = 100,
) -> Dict[str, Any]:
    """查询指定时间点前后的日志上下文。timestamp 必须是 ISO-8601 时间。"""
    try:
        if not 0 <= minutes_before <= 1440 or not 0 <= minutes_after <= 1440:
            raise ValueError("上下文时间范围必须在 0 到 1440 分钟之间")
        center = datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
        if center.tzinfo is None:
            center = center.replace(tzinfo=timezone.utc)
        return search_logs(
            query=query,
            index=index,
            start_time=(center - timedelta(minutes=minutes_before)).isoformat(),
            end_time=(center + timedelta(minutes=minutes_after)).isoformat(),
            size=size,
            sort_order="asc",
        )
    except Exception as exc:
        return _error(exc)


@server.tool()
def aggregate_logs(
    group_by: str,
    query: str = "",
    index: Optional[str] = None,
    start_time: Optional[str] = "now-1h",
    end_time: Optional[str] = "now",
    time_field: str = "@timestamp",
    filters: Optional[Dict[str, Any]] = None,
    limit: int = 20,
) -> Dict[str, Any]:
    """按服务、级别或主机等字段统计日志，仅读取聚合结果。"""
    try:
        _validate_name(group_by, "group_by", allow_comma=False)
        limit = min(_clean_size(limit), 100)
        raw = _run_search(
            index=index or _default_index(),
            query=query,
            start_time=start_time,
            end_time=end_time,
            time_field=time_field,
            filters=filters,
            size=0,
            source_fields=[],
            sort_order="desc",
            aggs={"groups": {"terms": {"field": group_by, "size": limit, "missing": "(missing)"}}},
        )
        return {"ok": True, "groups": _redact(raw.get("aggregations", {}).get("groups", {}).get("buckets", []))}
    except Exception as exc:
        return _error(exc)


if __name__ == "__main__":
    server.run(transport="stdio")
